//! Reusable Dioxus components for password handling.

// Icons: incluso se qualsiasi feature icons* è attiva
#[cfg(any(feature = "icons", feature = "icons-visibility",
          feature = "icons-action", feature = "icons-alert"))]
pub mod icons;

// ============================================================================
// CSS ASSETS FOR CONSUMER BUILD SYSTEMS
// ============================================================================

/// Custom CSS for pwd-dioxus components.
///
/// This CSS defines component-specific styles (spinner animations, toast
/// notifications, strength analyzer, etc.) that are NOT Tailwind classes.
///
/// ## Usage in Consumer Project
///
/// ### Option 1: Include in your Tailwind build (recommended)
///
/// In your build.rs, extract this CSS to a file before running Tailwind:
///
/// ```rust,ignore
/// use pwd_dioxus::COMPONENT_CSS;
/// std::fs::write("assets/pwd-dioxus-components.css", COMPONENT_CSS)?;
/// ```
///
/// Then in your CSS:
/// ```css
/// @import "./pwd-dioxus-components.css";
/// ```
///
/// ### Option 2: Include directly in main CSS
///
/// ```rust,ignore
/// // In your main.rs or component
/// const PWD_DIOXUS_CSS: &str = pwd_dioxus::COMPONENT_CSS;
/// ```
pub const COMPONENT_CSS: &str = include_str!("../assets/components.css");

/// Tailwind/DaisyUI classes used by pwd-dioxus components.
///
/// When pwd-dioxus is a git dependency, Tailwind cannot scan its source files
/// for class extraction. This list allows consumer projects to generate
/// the necessary Tailwind classes without needing access to the source files.
///
/// ## Usage in Consumer Project
///
/// In your build.rs, generate a CSS file with these classes:
///
/// ```rust,ignore
/// use pwd_dioxus::TAILWIND_CLASSES_USED;
///
/// let mut css_content = String::from("/* Auto-generated by pwd-dioxus */\n");
/// for class in pwd_dioxus::TAILWIND_CLASSES_USED {
///     css_content.push_str(&format!(".{} {{}}\n", class));
/// }
/// std::fs::write("assets/pwd-dioxus-classes.css", css_content)?;
/// ```
///
/// Then include in your Tailwind input CSS:
/// ```css
/// @source "./pwd-dioxus-classes.css";
/// ```
pub const TAILWIND_CLASSES_USED: &[&str] = &[
    // === DaisyUI Component Classes ===
    "btn",
    "btn-ghost",
    "btn-sm",
    "modal",
    "modal-box",
    "modal-backdrop",
    "form-label",
    "dropdown-content",
    "mockup-code",
    "tooltip",
    "bg-base-200",
    "bg-base-content",
    "text-base-content",
    "dropdown",
    "dropdown-open",

    // === Tailwind Layout ===
    "flex",
    "flex-col",
    "items-center",
    "items-start",
    "justify-center",
    "justify-end",
    "relative",
    "fixed",
    "absolute",

    // === Tailwind Spacing ===
    "gap-1",
    "gap-2",
    "gap-3",
    "p-3",
    "px-6",
    "py-4",
    "ml-1",
    "mt-2",

    // === Tailwind Sizing ===
    "min-w-[200px]",
    "inset-0",
    "w-6",
    "w-10",
    "w-14",
    "w-20",
    "w-50",
    "h-6",
    "h-10",
    "h-14",
    "h-20",
    "h-50",

    // === Tailwind Typography ===
    "text-xs",
    "text-sm",
    "text-current",
    "font-mono",
    "font-medium",
    "font-bold",

    // === Tailwind Colors (Text) ===
    "text-error",
    "text-error-500",
    "text-error-600",
    "text-gray-500",
    "text-blue-500",
    "text-blue-600",
    "text-success-500",
    "text-success-600",
    "text-warning-600",
    "text-purple-600",

    // === Tailwind Colors (Background) ===
    "bg-green-100",
    "bg-red-100",
    "bg-yellow-100",
    "bg-blue-100",
    "bg-primary-color/5",
    "bg-base-100",

    // === Tailwind Borders ===
    "rounded",
    "rounded-lg",
    "rounded-xl",
    "rounded-box",
    "border",
    "border-green-500",
    "border-red-500",
    "border-yellow-500",
    "border-blue-500",

    // === Tailwind Effects ===
    "shadow-lg",

    // === Tailwind Positioning ===
    "top-full",
    "left-0",
    "z-10",
    "z-[5]",
    "z-9999",
    "inset-0",

    // === Tailwind Misc ===
    "space-y-1",
    "backdrop-blur-sm",
    "transition-colors",
    "duration-150",
];

#[cfg(feature = "spinner")]
pub mod spinner;

#[cfg(feature = "modal")]
pub mod modal;

#[cfg(feature = "form")]
pub mod form;

#[cfg(feature = "secret-display")]
pub mod secret;

// password module: incluso per analyzer o handler
#[cfg(any(feature = "analyzer", feature = "handler"))]
pub mod password;

#[cfg(feature = "toast")]
pub mod toast;

#[cfg(feature = "toggle")]
pub mod toggle;

#[cfg(feature = "combobox")]
pub mod combobox;
// === RE-EXPORTS per convenienza ===

#[cfg(feature = "form")]
pub use form::{FormSecret, FormValue, InputType, SPECIAL_CHARS};

#[cfg(feature = "analyzer")]
pub use password::StrengthAnalyzer;

#[cfg(feature = "handler")]
pub use password::{PasswordHandler, EvaluationResult};

#[cfg(feature = "toggle")]
pub use toggle::{Toggle, ToggleColor, ToggleSize};

#[cfg(feature = "toast")]
pub use toast::{
    show_toast_error, show_toast_success, schedule_toast_success,
    ToastContainer, ToastHubState, ToastMessage, ToastType, use_toast,
};

// Re-export tipi pwd-types usati nelle API pubbliche
// I consumer possono usarli senza aggiungere pwd-types alle dipendenze
#[cfg(any(feature = "analyzer", feature = "handler"))]
pub use pwd_types::{PasswordScore, PasswordStrength};

#[cfg(feature = "handler")]
pub use pwd_types::PasswordChangeResult;

#[cfg(feature = "combobox")]
pub use combobox::{Combobox,AnyPreset};
